import { BaseLayout } from "@/components/layouts/baseLayout/baseLayout";
import { ArticleCategoryModul } from "@/modules/articleCategory/ArticleCategoryModul";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ArticleCategoryPage() {
  return (
    <div className="w-full">
      <BaseLayout>
        <ArticleCategoryModul />
      </BaseLayout>
    </div>
  );
}
