import { BaseLayout } from "@/components/layouts/baseLayout/baseLayout";
import { HomeModules } from "@/modules/homeModules/HomeModules";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="w-full">
      <BaseLayout>
        <HomeModules />
      </BaseLayout>
    </div>
  );
}
