import { BaseLayout } from "@/components/layouts/baseLayout/baseLayout";
import { ArticleDetailModul } from "@/modules/articleDetailModul/ArticleDetailModul";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ArticleDetailPage() {
  return (
    <div className="w-full">
      <BaseLayout>
        <ArticleDetailModul />
      </BaseLayout>
    </div>
  );
}
